config/routes.rb
Rails.application.routes.draw do
  resources :vs_demandes
  resources :demande_egs
  resources :motifs
  resources :parentinfos
  resources :notes
  resources :user_management
  resources :roles
  
  

  match '/familles/recherche', to: 'familles#rechercher', defaults: {format: 'json'}, via: [:post, :patchs]
  match '/demandes/ouverture/:id', to: 'demandes#ouverture', via: [:post], defaults: { format: 'html' }
  match '/demandes/ouverture', to: 'demandes#ouverture', via: [:get], defaults: { format: 'html' }
  match '/demandes/addParent/:id', to: 'demandes#addParent', via: [:post, :patchs]
  
  resources :familles
  resources :enfants
  resources :parents
  resources :demandes
  
  get 'welcome/index'
  root 'welcome#index'
  
  post "user_management/:id/edit" => "user_management#edit"
  put "user_management/:id/edit" => "user_management#update"
  
  get "user_management/new" => "user_management#new"
  post "user_management/new" => "user_management#create"
  
  devise_for :users, :controllers => { registrations: 'registration' }
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  default_url_options :host => "example.com"

end

app/models/famille.rb
class Famille < ActiveRecord::Base
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom de famille."}
	validates :dossier_id, :presence => {:message => "*Veuillez spécifier un numéro de dossier."}
	has_many :notes
	has_many :demandes, foreign_key: :famille_id, primary_key: :dossier_id
end

app/controllers/familles_controller.rb
class FamillesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_famille, only: [:show, :edit, :update, :destroy]

  # GET /familles
  # GET /familles.json
  def index
    @familles = Famille.all
  end

  # GET /familles/1
  # GET /familles/1.json
  def show
    @user = current_user
  end

  # GET /familles/new
  def new
    @famille = Famille.new
  end

  # GET /familles/1/edit
  def edit
  end

  # POST /familles
  # POST /familles.json
  def create
    @famille = Famille.new(famille_params)

    respond_to do |format|
      if @famille.save
        format.html { redirect_to @famille, notice: 'Famille was successfully created.' }
        format.json { render :show, status: :created, location: @famille }
	  else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /familles/1
  # PATCH/PUT /familles/1.json
  def update
    respond_to do |format|
      if @famille.update(famille_params)
        format.html { redirect_to @famille, notice: 'Famille was successfully updated.' }
        format.json { render :show, status: :ok, location: @famille }
	  else
        format.html { render :edit }
      end
    end
  end

  def rechercher

    typeDeRecherche = params[:typeDeRecherche]
    valeurDeRecherche  = params[:valeurDeRecherche]

    case typeDeRecherche 
      when "1"
         string = 'SELECT familles.id, familles.nom FROM familles 
                  LEFT JOIN demandes ON demandes.famille_id = dossier_id
                  WHERE TRUE
                  AND demandes.id='+valeurDeRecherche

      when "2"
         string = "SELECT familles.id, familles.nom FROM familles 
                  LEFT JOIN demandes ON demandes.famille_id = dossier_id
                  LEFT JOIN parents AS parent on demandes.id = parent.demande_id 
                  WHERE TRUE 
                  AND parent.nom='"+valeurDeRecherche+"'"

      when "3"
         #À completer, table référent n'existe pas encore + requête
      when "4"
        string = "SELECT familles.id, familles.nom FROM familles 
                  LEFT JOIN demandes ON demandes.famille_id = dossier_id 
                  LEFT JOIN enfants AS enfant ON demandes.id = enfant.demande_id
                  WHERE TRUE
                  AND enfant.nom='"+ valeurDeRecherche +"'"
    end

    connection = Demande.connection
    array = connection.select_all(string)
    respond_to do |format|
      format.json { render json: array, status: :ok }
    end
  end


  # DELETE /familles/1
  # DELETE /familles/1.json
  def destroy
    string = "DELETE FROM notes WHERE famille_id = #{@famille.id}"
    connection = Demande.connection
    connection.delete(string)
    @famille.destroy
    respond_to do |format|
      format.html { redirect_to familles_url, notice: 'Famille was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_famille
      @famille = Famille.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def famille_params
      params.require(:famille).permit(:nom, :id, :dossier_id)
    end
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/views/familles/_form.html.erb
<%= simple_form_for(@famille) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom %>
  </div>
  
  <div class="form-inputs">
    <%= f.input :dossier_id, :label => "Numéro de dossier" %>
  </div>
  
  <div class="form-inputs">
    <%= f.input :statut %>
  </div>

  <div class="form-actions">
    <%= f.submit "Sauvegarder" %>
  </div>
<% end %>

app/views/familles/edit.html.erb
<h1>Modification de famille</h1>

<%= render 'form', famille: @famille %>

<%= link_to 'Détails', @famille %> |
<%= link_to 'Retour à la famille', famille_path(@famille.id) %>

app/views/familles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Familles</h1>
<form id="rechercheFamille" action="recherche">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <select id="typeDeRecherche">
    <option value="1">Numéro de dossier</option>
    <option value="2">Parent</option>
    <option value="3">Référent</option>
    <option value="4">Enfant</option>
  </select>
  <input type="text" id="valeurDeRecherche"> </input>
  <input type="submit" id="submitRecherche" value="Rechercher"> </input>
</form>

<table id="familleTable">
  <thead>
    <tr>
      <th>Nom</th>
	  <th>Numéro de dossier</th>
	  <th>Statut</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="familleBody">
    <% @familles.each do |famille| %>
      <tr id="famille_<%= famille.id %>">
        <td><%= famille.nom %></td>
		<td><%= famille.dossier_id %></td>
		<td><%= famille.statut %></td>
        <td><%= link_to 'Détails', famille %></td>
        <td><%= link_to 'Modifier', edit_famille_path(famille) %></td>
        <td><%= button_to 'Supprimer', famille, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Créer', new_famille_path %>
<script type="text/javascript">
  function ajaxRecherche() {
      $("#familleBody tr").remove();
      var valuesToSubmit = {
        typeDeRecherche: $("#typeDeRecherche").val(),
        valeurDeRecherche: $("#valeurDeRecherche").val(),
        authenticity_token: $("[name ='authenticity_token']")[0].value
      };
      console.log(valuesToSubmit);
      var requete = $.ajax({
          type: "POST",
          url: $(this).attr('action'),
          data: valuesToSubmit,
          dataType: "JSON"
      });
      requete.done(function(json){
          
          $.each(json, function(index) {
            $("#familleBody").append(
              $("<tr>").append(
                $("<td>").text(this.nom)
              ).append(
                $("<td>").append(
                  $("<a>").text("edit").attr("href", "/familles/" + this.id + "/edit")
                )
              )
            );
            console.log(this);
          })
      });
      return false;
  }

  $("#rechercheFamille").submit(ajaxRecherche);
  </script>

app/views/familles/new.html.erb
<h1>Création de famille</h1>

<%= render 'form', famille: @famille %>

<%= link_to 'Retour à la liste des familles', familles_path %>

app/views/familles/show.html.erb
<h1>Détails de famille</h1>

<p id="notice"><%= notice %></p>
<p>
  <strong>Nom:</strong>
  <%= @famille.nom %>
</p>

<p>
  <strong>Numéro de dossier:</strong>
  <%= @famille.dossier_id %>
</p>

<p>
  <strong>Statut:</strong>
  <%= @famille.statut %>
</p>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Intervenant</th>
      <th>Date de création</th>
   </tr>
  </thead>

  <tbody>
	<h3>Liste de notes</h3>
    <% @famille.notes.each do |note| %>
      <tr>
        <td><%= note.texte %></td>
        <% if (!note.users_id.nil?) %>
          <td><%= User.find(note.users_id).name %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= note.dateCreation %></td>
        <td><%= link_to 'Modifier', edit_note_path(note) %></td>
        <td><%= button_to 'Supprimer', note, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= simple_form_for(Note.new) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.hidden_field :famille_id, :value => @famille.id %>
    <% if !@user.nil? %>
      <%= f.hidden_field :users_id, :value => @user.id %>
    <% end %>
    <%= f.input :texte, :label => "Note" %>
  </div>

  <div class="form-actions">
    <%= f.submit "Ajouter une note" %>
  </div>
<% end %>

<%= link_to 'Modifier', edit_famille_path(@famille) %> |
<%= link_to 'Retour à la liste des familles', familles_path %>