config/routes.rb
Rails.application.routes.draw do
  resources :vs_demandes
  resources :demande_egs
  resources :motifs
  resources :parentinfos
  resources :notes
  resources :user_management
  resources :roles
  
  

  match '/familles/recherche', to: 'familles#rechercher', defaults: {format: 'json'}, via: [:post, :patchs]
  match '/demandes/ouverture/:id', to: 'demandes#ouverture', via: [:post], defaults: { format: 'html' }
  match '/demandes/ouverture', to: 'demandes#ouverture', via: [:get], defaults: { format: 'html' }
  match '/demandes/addParent/:id', to: 'demandes#addParent', via: [:post, :patchs]
  
  resources :familles
  resources :enfants
  resources :parents
  resources :demandes
  
  get 'welcome/index'
  root 'welcome#index'
  
  post "user_management/:id/edit" => "user_management#edit"
  put "user_management/:id/edit" => "user_management#update"
  
  get "user_management/new" => "user_management#new"
  post "user_management/new" => "user_management#create"
  
  devise_for :users, :controllers => { registrations: 'registration' }
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  default_url_options :host => "example.com"

end

app/models/demande.rb
class Demande < ActiveRecord::Base
	enum service: {VS: "VS", EG: "EG", CTS: "CTS"}
	
	has_many :vs_demandes
	has_many :demande_egs
    has_many :demande_enfants
    belongs_to :famille, foreign_key: :famille_id, primary_key: :dossier_id
	belongs_to :motif
	belongs_to :user
	
	validates :service, :presence => {:message => "*Veuillez spécifier un service"}
	validates :famille_id, :presence => {:message => "*Veuillez spécifier une famille"}
	validates :frequence, :presence => {:message => "*Veuillez spécifier une fréquence"}
	validates :demandeur, :presence => {:message => "*Veuillez spécifier un demandeur"}
	validates :payee_par, :presence => {:message => "*Veuillez spécifier la personne qui paie"}
	validates :motif_id, :presence => {:message => "*Veuillez spécifier un motif"}
end

app/models/demande_eg.rb
class DemandeEg < ActiveRecord::Base
	belongs_to :demande
	validates :motif, :presence => {:message => "*Veuillez spécifier un motif"}
	validates :date_separation, :presence => {:message => "*Veuillez spécifier une date de séparation."}
	validates :description_enfant, :presence => {:message => "*Veuillez spécifier une description de l'enfant."}
	validates :attitude_parent, :presence => {:message => "*Veuillez spécifier l'attitude du parent."}
	validates :attitude_enfant, :presence => {:message => "*Veuillez spécifier l'attitude de l'enfant."}
end

app/models/enfant.rb
class Enfant < ActiveRecord::Base
	has_many :demandes

	validates :residence, :presence => {:message => "*Veuillez spécifier une résidence."}
	validates :nom, :presence => {:message => "*Veuillez spécifier le nom de l'enfant."}
	validates :date_naissance, :presence => {:message => "*Veuillez spécifier la date de naissance."}
end

app/models/famille.rb
class Famille < ActiveRecord::Base
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom de famille."}
	validates :dossier_id, :presence => {:message => "*Veuillez spécifier un numéro de dossier."}
	has_many :notes
	has_many :demandes, foreign_key: :famille_id, primary_key: :dossier_id
end

app/models/motif.rb
class Motif < ActiveRecord::Base
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom de motif."}
	has_many :demande
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :texte,      :presence => {:message => "*Veuillez spécifier du texte."}	
	validates :famille_id, :presence => {:message => "*Veuillez spécifier une famille."}
	validates :users_id,   :presence => {:message => "*Veuillez spécifier un utilisateur."}
	
	belongs_to :famille,  :foreign_key => "familles_id"
	belongs_to :createur, :class_name => "User", :foreign_key => "user_id"
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	enum statut: [:gardien, :tuteur, :visiteur, :acceuil]
	has_many :demandes

	has_many :parentinfos
    accepts_nested_attributes_for :parentinfos

	validates :statut, :presence => {:message => "*Veuillez spécifier un statut."}
	validates :date_naissance, :presence => {:message => "*Veuillez spécifier une date de naissance."}
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom."}
	validates :demande_id, :presence => {:message => "*Veuillez spécifier un numéro de demande."}
end

app/models/parentinfo.rb
class Parentinfo < ActiveRecord::Base
	belongs_to :parent
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  belongs_to :role
  has_many :notes
  has_many :demandes
  validates :name, presence: true, length: { maximum: 50, minimum: 5, message: 'Le nom doit être entre 5 et 50 caractères' }
end

app/models/vs_demande.rb
class VsDemande < ActiveRecord::Base
	belongs_to :demande

	validates :motif_pv, :presence => {:message => "*Veuillez spécifier un motif"}
	validates :motivations_pv, :presence => {:message => "*Veuillez spécifier une motivation."}
	validates :attitude_parent_pv, :presence => {:message => "*Veuillez spécifier une attitude."}
	validates :motif_pg, :presence => {:message => "*Veuillez spécifier le motif."}
	validates :personnes_autorisees_pg, :presence => {:message => "*Veuillez spécifier les personnes autorisées"}
	validates :attitude_parent_pg, :presence => {:message => "*Veuillez spécifier une attitude"}
	validates :jeux_favoris_pg, :presence => {:message => "*Veuillez spécifier les jeux favoris."}
	validates :gout_alimentaire_pg, :presence => {:message => "*Veuillez spécifier les gouts alimentaires."}
	validates :reaction_visite_pg, :presence => {:message => "*Veuillez spécifier la réaction."}
	validates :attitude_enfant_pg, :presence => {:message => "*Veuillez spécifier l'attitude."}

end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_enfant, only: [:show, :edit, :update, :destroy]

  # GET /enfants
  # GET /enfants.json
  def index
    @enfants = Enfant.all
  end

  # GET /enfants/1
  # GET /enfants/1.json
  def show
  end

  # GET /enfants/new
  def new
    @enfant = Enfant.new
	  if params.has_key?(:demande_id)
		  @enfant.demande_id = params[:demande_id]
	  end
  end

  # GET /enfants/1/edit
  def edit
  end

  # POST /enfants
  # POST /enfants.json
  def create
    @enfant = Enfant.new(enfant_params)

    respond_to do |format|
      if @enfant.save
        format.html { redirect_to @enfant, notice: 'Enfant was successfully created.' }
        format.json { render :show, status: :created, location: @enfant }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /enfants/1
  # PATCH/PUT /enfants/1.json
  def update
    respond_to do |format|
      if @enfant.update(enfant_params)
        format.html { redirect_to @enfant, notice: 'Enfant was successfully updated.' }
        format.json { render :show, status: :ok, location: @enfant }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /enfants/1
  # DELETE /enfants/1.json
  def destroy
    @enfant.destroy
    respond_to do |format|
      format.html { redirect_to enfants_url, notice: 'Enfant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enfant_params
      params.require(:enfant).permit(:enfantId, :date_naissance, :residence, :nom, :demande_id, :allergies, :personnes_auth, :renseignements, :no_RAMQ)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demande_egs_helper.rb
module DemandeEgsHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/helpers/motifs_helper.rb
module MotifsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parentinfos_helper.rb
module ParentinfosHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/vs_demandes_helper.rb
module VsDemandesHelper
end

app/views/enfants/_form.html.erb
<%= simple_form_for(@enfant) do |f| %>

<div class="form-inputs">

    <%= f.input :date_naissance, :label => "Date de naissance" %>

    <%= f.input :residence, :label => "Résidence" %>

    <%= f.input :nom %>
  
    <%= f.input :allergies %>
  
    <%= f.input :personnes_auth, :label => "Personnes autorisées à reconduire l'enfant" %>
  
    <%= f.input :renseignements %>

    <%= f.input :no_RAMQ, :label => "No RAMQ" %>
  
  <% if !@enfant.demande_id.nil? %>
    <%= f.hidden_field :demande_id %>
  <% else %>
    <%= f.input :demande_id %>
  <% end %>

  <div class="form-actions">
    <%= f.submit "Sauvegarder" %>
  </div>
<% end %>

app/views/enfants/edit.html.erb
<h1>Modification d'enfant</h1>

<%= render 'form' %>

<%= link_to 'Retour à l\'enfant', @enfant %>

app/views/enfants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enfants</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Age</th>
      <th>Residence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enfants.each do |enfant| %>
      <tr>
        <td><%= enfant.nom %></td>
        <td><%= enfant.date_naissance %></td>
        <td><%= enfant.residence %></td>
        <td><%= link_to 'Show', enfant %></td>
        <td><%= link_to 'Edit', edit_enfant_path(enfant) %></td>
        <td><%= button_to 'Destroy', enfant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/enfants/new.html.erb
<h1>Création d'enfant</h1>

<%= render 'form' %>

<%= link_to 'Retour à la demande', demande_path(@enfant.demande_id) %>

app/views/enfants/show.html.erb
<h1>Détails d'enfant</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @enfant.nom %>
</p>

<p>
  <strong>Date de naissance:</strong>
  <%= @enfant.date_naissance %>
</p>

<p>
  <strong>Référents:</strong> <br>
  <%= link_to "Ajouter un référent", "http://hidden-basin-94586.herokuapp.com/referents/" %>
</p>

<p>
  <strong>Résidence:</strong>
  <%= @enfant.residence %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @enfant.allergies %>
</p>

<p>
  <strong>Personnes autorisées à reconduire l'enfant:</strong>
  <%= @enfant.personnes_auth %>
</p>

<p>
  <strong>Renseignements:</strong>
  <%= @enfant.renseignements %>
</p>

<p>
  <strong>No RAMQ:</strong>
  <%= @enfant.no_RAMQ %>
</p>

<%= link_to 'Modifier', edit_enfant_path(@enfant) %> |
<%= link_to 'Retour à la demande', demande_path(@enfant.demande_id) %>