config/routes.rb
Rails.application.routes.draw do
  resources :vs_demandes
  resources :demande_egs
  resources :motifs
  resources :parentinfos
  resources :notes
  resources :user_management
  resources :roles
  
  

  match '/familles/recherche', to: 'familles#rechercher', defaults: {format: 'json'}, via: [:post, :patchs]
  match '/demandes/ouverture/:id', to: 'demandes#ouverture', via: [:post], defaults: { format: 'html' }
  match '/demandes/ouverture', to: 'demandes#ouverture', via: [:get], defaults: { format: 'html' }
  match '/demandes/addParent/:id', to: 'demandes#addParent', via: [:post, :patchs]
  
  resources :familles
  resources :enfants
  resources :parents
  resources :demandes
  
  get 'welcome/index'
  root 'welcome#index'
  
  post "user_management/:id/edit" => "user_management#edit"
  put "user_management/:id/edit" => "user_management#update"
  
  get "user_management/new" => "user_management#new"
  post "user_management/new" => "user_management#create"
  
  devise_for :users, :controllers => { registrations: 'registration' }
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  default_url_options :host => "example.com"

end

app/models/demande.rb
class Demande < ActiveRecord::Base
	enum service: {VS: "VS", EG: "EG", CTS: "CTS"}
	
	has_many :vs_demandes
	has_many :demande_egs
    has_many :demande_enfants
    belongs_to :famille, foreign_key: :famille_id, primary_key: :dossier_id
	belongs_to :motif
	belongs_to :user
	
	validates :service, :presence => {:message => "*Veuillez spécifier un service"}
	validates :famille_id, :presence => {:message => "*Veuillez spécifier une famille"}
	validates :frequence, :presence => {:message => "*Veuillez spécifier une fréquence"}
	validates :demandeur, :presence => {:message => "*Veuillez spécifier un demandeur"}
	validates :payee_par, :presence => {:message => "*Veuillez spécifier la personne qui paie"}
	validates :motif_id, :presence => {:message => "*Veuillez spécifier un motif"}
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_demande, only: [:createUpdate, :show, :edit, :update, :destroy, :addParent]

  # GET /demandes
  # GET /demandes.json
  def index
    @demandes = Demande.all
	
	@demandes.each do |d|
		if d.statut == "Non complété" # I'm lovin' it.
			@gardiens = Parent.where(["demande_id = ? AND (statut = ? OR statut = ? OR statut = ?)", d.id, 0, 1, 3])
			@visiteurs = Parent.where(["demande_id = ? AND statut = ?", d.id, 2])
			if (@gardiens + @visiteurs).size >= 2
				d.update_attributes(:statut => "Complété")
			end
		end
	end
  end

  # GET /demandes/1
  # GET /demandes/1.json
  def show
    @gardiens = Parent.where(["demande_id = ? AND (statut = ? OR statut = ? OR statut = ?)", @demande.id, 0, 1, 3])
    @visiteurs = Parent.where(["demande_id = ? AND statut = ?", @demande.id, 2])
  end

  # GET /demandes/new
  def new
  end

  def addParent
    Parent.new()
    
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: @demande, status: :ok }
    end
  end
  
#  def ouverture
#    if Demande.exists?(params[:id])
#      @demande = Demande.find(params[:id])
#    else
#      @demande = Demande.new()
#      @demande.gardien = Parent.new()
#    end
#  end

def ouverture
    if params[:id].nil?
      @demande = Demande.new()
    else
      @demande = Demande.find(params[:id])
    end
  end

  def new
    redirect_to action: "ouverture"
  end

  # GET /demandes/1/edit
  def edit
    @gardiens = Parent.where(["demande_id = ? AND (statut = ? OR statut = ? OR statut = ?)", @demande.id, 0, 1, 3])
    @visiteurs = Parent.where(["demande_id = ? AND statut = ?", @demande.id, 2])
    @parents = @gardiens + @visiteurs
    @enfants = Enfant.where("demande_id = ?", @demande.id)
  end

  # POST /demandes
  # POST /demandes.json
  def create
    @demande = Demande.new(demande_params)
    respond_to do |format|
      if @demande.save
        format.html { redirect_to @demande, notice: 'Demande was successfully updated.' }
        format.json { render json: @demande, status: :created, location: @demande , :layout => false}
	  else
	    format.html { render :new }
      end
    end
  end

  # PATCH/PUT /demandes/1
  # PATCH/PUT /demandes/1.json
  def update
    respond_to do |format|
      if @demande.update(demande_params)
        format.html { redirect_to @demande, notice: 'Demande was successfully updated.' }
        format.json { render :show, status: :ok, location: @demande }
	  else
	    format.html { render :edit }
      end
    end
  end

  # DELETE /demandes/1
  # DELETE /demandes/1.json
  def destroy
    @demande.destroy
    respond_to do |format|
      format.html { redirect_to demandes_url, notice: 'Demande was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demande
      if(!params.has_key?(:id) || params[:id] == 'new')
        @demande = nil
      else
        @demande = Demande.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demande_params
      params.require(:demande).permit(:demande_id, :service, :famille_id, :created_at, :frequence, :statut, :demandeur, :payee_par, :refere_par, :transport, :motif_id, :user_id)
    end
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/views/demandes/_form.html.erb
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBE1pI65C_sCNOqcSRhIRM9DzqzzJYbIKQ">
	
</script>

<div class="descriptionRQRSDA">

	<%= simple_form_for(demande, remote: true, format: :json) do |f| %>
	  <% if demande.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(demande.errors.count, "error") %> prohibited this demande from being saved:</h2>

		  <ul>
		  <% demande.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>
	  
	  <%= f.hidden_field :user_id, :value => !current_user.nil?? current_user.id : -1 %>
	  <%= f.hidden_field :statut, :value => "Non complété" %>

	  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

	  <%= f.input :demande_id, :label => "Identifiant" %>

	  <%= f.input :famille_id, :label => "Identifiant de la famille" %>
	  
	  <%= f.input :frequence, :label => "Fréquence" %>
	  
	  <%= f.input :service, :label => "Service" %>
	  
	  <%= f.input :demandeur, :label => "Demandeur" %>
	  
	  <%= f.input :payee_par, :label => "Payée par" %>
	  
	  <%= f.input :transport, :label => "Transport" %>
	  
	  <%= f.input :refere_par, :label => "Référé par" %>
	  
	  <div class="field">
		<%= f.label :motif_id %>
		<select id="demande[motif_id]" name="demande[motif_id]">
			<option value=""></option>
			<% Motif.find_each do |m| %>
				<option value="<%= m.id %>" <%= m.id == @demande.motif_id ? "selected" : "" %>><%= m.nom %></option> <!-- Fuck Rails. -->
			<% end %>
		</select>
	  </div>

	  <div class="actions">
		<%= f.submit "Sauvegarder" %>
	  </div>
	<% end %>

	<%= tag(:input, :type => "hidden", :name => 'demande_id', :value => demande.id) %>

	<% @compteur = "0" %>

	<% if (@gardiens.nil?) || (@visiteurs.nil? && @gardiens.size < 2) || (@gardiens.size + @visiteurs.size < 2) %>
		<% @compteur = (@compteur.to_i + 1).to_s %>

		<%= simple_form_for Parent.new, :namespace => @compteur do |g| %>
		  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

		  <%= g.hidden_field :demande_id, :value => demande.id %>
		  
		  <%= g.input :nom, :label => "Nom" %>

		  <%= g.input :statut %>
		  
		  <%= g.input :date_naissance, :label => "Date de naissance" %>
		  
		  <%= g.input :tarification, :label => "Tarification" %>
		  
		  <%= g.input :no_permis_conduire, :label => "No permis de conduire" %>
		  
		  <%= g.input :no_RAMQ, :label => "No RAMQ" %>
		  
		  <%= g.input :avocat, :label => "Avocat" %>
		  
		  <%= g.input :avocatTelephone, :label => "No téléphone de l'avocat" %>
		  
		  <%= g.simple_fields_for :parentinfos, Parentinfo.new do |f| %>
			  <%= f.input :courriel, :label => "Courriel" %>

			  <%= f.input :telephone_res, :label => "No téléphone résidentiel" %>
			  
			  <%= f.input :telephone_travail, :label => "No téléphone travail" %>
			  
			  <%= f.input :telephone_cell, :label => "No téléphone cellulaire" %>

			  <%= f.input :nocivique, :label => "No civique" %>

			  <%= f.input :rue, :label => "Rue" %>

			  <%= f.input :appartement, :label => "Appartement" %>

			  <%= f.input :ville, :label => "Ville" %>

			  <%= f.input :code_postal, :label => "Code postal" %>

			  <div class="field">
				<input type="button" name="show" value="Rechercher l'adresse" id=<%= @compteur %> />
			  </div>

			  <%= f.input :province, :label => "Province" %>

			  <%= f.input :nom_urgence, :label => "Nom de la personne en cas d'urgence" %>

			  <%= f.input :numero_urgence, :label => "No téléphone de la personne en cas d'urgence" %>

			  <%= f.input :note, :label => "Note" %>
		  <% end %>

		  <div class="actions">
			<%= g.submit "Créer" %>
		  </div>
		<% end %>
	<% end %>
	<br><br>
	<% if (!@gardiens.nil?) || (!@visiteurs.nil?) %>
		<% @parents.each do |parent| %>
			<% @compteur = (@compteur.to_i + 1).to_s %>
			<%= simple_form_for parent, :namespace => @compteur do |g| %>
			  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

			  <%= g.hidden_field :demande_id, :value => demande.id %>
			  
			  <%= g.input :nom, :label => "Nom" %>

			  <%= g.input :statut %>
			  
			  <%= g.input :date_naissance, :label => "Date de naissance" %>
			  
			  <%= g.input :tarification, :label => "Tarification" %>
			  
			  <%= g.input :no_permis_conduire, :label => "No permis de conduire" %>
			  
			  <%= g.input :no_RAMQ, :label => "No RAMQ" %>
			  
			  <%= g.input :avocat, :label => "Avocat" %>
			  
			  <%= g.input :avocatTelephone, :label => "No téléphone de l'avocat" %>

			  <%= g.simple_fields_for :parentinfos, parent.parentinfos.where("created_at = (SELECT MAX(created_at) FROM parentinfos WHERE parent_id = ?)", parent.id) do |f| %>
				  <%= f.input :courriel, :label => "Courriel" %>

				  <%= f.input :telephone_res, :label => "No téléphone résidentiel" %>
				  
				  <%= f.input :telephone_travail, :label => "No téléphone travail" %>
				  
				  <%= f.input :telephone_cell, :label => "No téléphone cellulaire" %>

				  <%= f.input :nocivique, :label => "No civique" %>

				  <%= f.input :rue, :label => "Rue" %>

				  <%= f.input :appartement, :label => "Appartement" %>

				  <%= f.input :ville, :label => "Ville" %>

				  <%= f.input :code_postal, :label => "Code postal" %>

				  <div class="field">
					<input type="button" name="show" value="Rechercher l'adresse" id=<%= @compteur %> />
				  </div>

				  <%= f.input :province, :label => "Province" %>

				  <%= f.input :nom_urgence, :label => "Nom de la personne en cas d'urgence" %>

				  <%= f.input :numero_urgence, :label => "No téléphone de la personne en cas d'urgence" %>

				  <%= f.input :note, :label => "Note" %>
			  <% end %>

			  <div class="actions">
				<%= g.submit "Créer" %>
			  </div>
			<% end %>
		<% end %>
	<% end %>

	<div class='buttonEnfant'>
		<% if !@enfants.nil? %>
			<% @enfants.each do |enfant| %>
				<b>Nom de l'enfant : </b> <%= enfant.nom %> <br>
			<% end %>
		<% end %>
	</div>
	<%= button_to 'Ajouter enfants', new_enfant_path, {class: 'buttonEnfant', method: :get, params: {demande_id: :demande_id} } %>
	
</div>
<div style="clear:both;"></div>

<script type="text/javascript"> 
  $('.new_parent').hide();
  $('.edit_parent').hide();
  function ajaxDemande() {  
      var valuesToSubmit = $(this).serialize();
      var requete = $.ajax({
          type: "POST",
          url: $(this).attr('action'),
          data: valuesToSubmit,
          dataType: "JSON"
      });
      requete.done(function(json){
          $("#messageH2").text('Réussite');
          $('.new_parent').show();
          $('.edit_parent').show();
          $('.new_demande').hide();
          $('.edit_demande').hide();
          $("[name=demande_id]").val(json.id);
          $("#1_parent_demande_id").val(json.id);
      });
      requete.fail(function(json){
          $("#messageH2").text('Une Erreure est survenue');
      });
      return false;
  }

  function ajaxParent() {  
      var valuesToSubmit = $(this).serialize();
      var requete = $.ajax({
          type: "POST",
          url: $(this).attr('action'),
          data: valuesToSubmit,
          dataType: "JSON"
      });
      requete.done(function(json){
          var requete = $.ajax({
            type: "POST",
            url: '/demandes/addParent/' + $("[name=demande_id]").val(),
            data: {
              parent_id: json.id,
              parent_statut: json.statut,
              demande_id: $("[name=demande_id]").val(),
              authenticity_token: $("[name=authenticity_token]").val(),
            },
            dataType: "JSON"
          });
          requete.done(function(json){
            $("#messageH2").text('Réussite ajout parent');
            $('.buttonEnfant').show();
            $('.new_parent').hide();
            $('.edit_parent').hide();
			location.href = "https://log210-02groupe2.herokuapp.com/users/5/disponibilites"
			
          });
          requete.fail(function(json){
            $("#messageH2").text('Une Erreure est survenue');
          });
      });
      requete.fail(function(json){
          $("#messageH2").text('Une Erreure est survenue');
      });
      return false;
  }
  $(".new_demande").submit(ajaxDemande);
  $(".edit_demande").submit(ajaxDemande);
  $(".new_parent").submit(ajaxParent);
  $(".edit_parent").submit(ajaxParent);
  </script>

  <script>
	$("[name='show']").click(function(){
		var location = $('#' + this.id +'_parent_parentinfos_attributes_0_code_postal').val();
		getAddress(location, this.id);
		});

		function getAddress(location, id){
		geocoder = new google.maps.Geocoder();
		geocoder.geocode( { 'address': location }, function(results, status) {
		if (status == 'OK') {
			var resultat = results[0].formatted_address.split(',');
			var resultat2 = resultat[1].split(' ');

			$('#' + id +'_parent_parentinfos_attributes_0_ville').val(resultat[0]);

			$('#' + id +'_parent_parentinfos_attributes_0_province').val(resultat2[1]);

		} else {

			alert("Le code postal n'existe pas.");
		}
		});
	}
    </script>

app/views/demandes/edit.html.erb
<h1>Modification de dossier</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Détails', @demande %> |
<%= link_to 'Retour à la liste des demandes', demandes_path %>

app/views/demandes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titleRQRSDA">Demandes</h1>
<div class="descriptionRQRSDA">
	<table>
	  <thead>
		<tr>
		  <th>Identifiant</th>
		  <th>Nom de l'intervenant</th>
		  <th>Identifiant de la famille</th>
		  <th>Service</th>
		  <th>Date de création</th>
		  <th>Fréquence</th>
		  <th>Statut</th>
		  <th>Demandeur</th>
		  <th>Payée par</th>
		  <th>Transport</th>
		  <th>Référé par</th>
		  <th>Motif</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @demandes.each do |demande| %>
		  <tr>
			<td><%= demande.demande_id %></td>
			<td><%= !demande.user.nil?? demande.user.name : "" %></td>
			<td><%= demande.famille_id %></td>
			<td><%= demande.service %></td>
			<td><%= demande.created_at %></td>
			<td><%= demande.frequence %></td>
			<td><%= demande.statut %></td>
			<td><%= demande.demandeur %></td>
			<td><%= demande.payee_par %></td>
			<td><%= demande.transport %></td>
			<td><%= demande.refere_par %></td>
			<td><%= !demande.motif.nil?? demande.motif.nom : "" %></td>
			<td><%= link_to 'Détails', demande %></td>
			<td><%= link_to 'Modifier', edit_demande_path(demande) %></td>
			<td><%= button_to 'Supprimer', demande, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
</div>
<div style="clear:both;">

<br>

<%= link_to 'Créer', new_demande_path %> |
<%= link_to 'Gestion des motifs', motifs_path %>

app/views/demandes/new.html.erb
<h1>Nouvelle Demande</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Retour à la liste des demandes', demandes_path %>

app/views/demandes/ouverture.html.erb
<h1>Ouverture de dossier</h1>

<h2 id="messageH2"></h2>
<%= render 'form', demande: @demande %>
<%= link_to 'Retour à la liste des demandes', demandes_path %>

app/views/demandes/show.html.erb
<h1>Détails de dossier</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Identifiant:</strong>
  <%= @demande.demande_id %>
</p>

<p>
  <strong>Nom de l'intervenant:</strong>
  <%= !@demande.user.nil?? @demande.user.name : "" %>
</p>

<p>
  <strong>Identifiant de la famille:</strong>
  <%= @demande.famille_id %>
</p>

<p>
  <strong>Service:</strong>
  <%= @demande.service %>
</p>

<p>
  <strong>Date de création:</strong>
  <%= @demande.created_at %>
</p>

<p>
  <strong>Fréquence:</strong>
  <%= @demande.frequence %>
</p>

<p>
  <strong>Statut:</strong>
  <%= @demande.statut %>
</p>

<p>
  <strong>Demandeur:</strong>
  <%= @demande.demandeur %>
</p>

<p>
  <strong>Payée par:</strong>
  <%= @demande.payee_par %>
</p>

<p>
  <strong>Référé par:</strong>
  <%= @demande.refere_par %>
</p>

<p>
  <strong>Transport:</strong>
  <%= @demande.transport %>
</p>

<p>
  <strong>Motif:</strong>
  <%= !@demande.motif.nil?? @demande.motif.nom : "" %>
</p>

<p>
  <% if !@gardiens.nil? %>
    <% if !@gardiens.empty? %>
      <% @gardiens.each do |gardien| %>
        <strong>gardien: </strong> <%= gardien.nom %>
		<%= link_to 'Détails', gardien %><br>
      <% end %>
    <% end %>
  <% end %>
</p>

<p>
  <% if !@visiteurs.nil? %>
    <% if !@visiteurs.empty? %>
      <% @visiteurs.each do |visiteur| %>
        <strong>visiteur: </strong> <%= visiteur.nom %>
		<%= link_to 'Détails', visiteur %><br>
      <% end %>
    <% end %>
  <% end %>
</p>
<% if !@visiteurs.nil? %>
  <% if (@gardiens.size + @visiteurs.size) < 2 %>
    <%= button_to "Ajouter un parent", {:controller => "demandes", :action => "addParent", :id => @demande.id} %>
  <% end %>
<% end %>

<p>
  <strong>Enfants:</strong>
  <br>
  <% Enfant.find_each do |e| %>
    <% if e.demande_id == @demande.id %>
	  <%= e.nom %>
	  <%= link_to 'Détails', e %>
	  <br>
    <% end %>
  <% end %>
  <%= button_to "Ajouter un enfant", new_enfant_path, {class: '', method: :get, params: {demande_id: @demande.id} } %> <!-- Yep. -->
</p>

<% if @demande.service == "EG" %>
	<p>
	  <strong>Demandes EG:</strong>
	  <br>
	  <% if current_user.role_id == 0 || current_user.role_id == 1 %>
		<%= button_to 'Ajouter un formulaire', new_demande_eg_path, {class: '', method: :get, params: {demande_id: @demande.id} } %>
	  <% end %>
	  <% @demande.demande_egs.each do |eg| %>
		<%= eg.id %>
		<%= link_to 'Détails', eg %>
		<br>
	  <% end %>
	</p>
<% elsif @demande.service == "VS" %>
	<p>
	  <strong>Demandes VS:</strong>
	  <br>
	  <% if current_user.role_id == 0 || current_user.role_id == 1 %>
		<%= button_to 'Ajouter un formulaire', new_vs_demande_path, {class: '', method: :get, params: {demande_id: @demande.id} } %>
	  <% end %>
	  <% @demande.vs_demandes.each do |vs| %>
		<%= vs.id %>
		<%= link_to 'Détails', vs %>
		<br>
	  <% end %>
	</p>
<% end %>

<%= link_to 'Modifier', edit_demande_path(@demande) %> |
<%= link_to 'Gestion Documentaire', 'https://gestion-documentation.herokuapp.com/' %> |
<%= link_to 'Retour à la liste des demandes', demandes_path %>