config/routes.rb
Rails.application.routes.draw do
  resources :vs_demandes
  resources :demande_egs
  resources :motifs
  resources :parentinfos
  resources :notes
  resources :user_management
  resources :roles
  
  

  match '/familles/recherche', to: 'familles#rechercher', defaults: {format: 'json'}, via: [:post, :patchs]
  match '/demandes/ouverture/:id', to: 'demandes#ouverture', via: [:post], defaults: { format: 'html' }
  match '/demandes/ouverture', to: 'demandes#ouverture', via: [:get], defaults: { format: 'html' }
  match '/demandes/addParent/:id', to: 'demandes#addParent', via: [:post, :patchs]
  
  resources :familles
  resources :enfants
  resources :parents
  resources :demandes
  
  get 'welcome/index'
  root 'welcome#index'
  
  post "user_management/:id/edit" => "user_management#edit"
  put "user_management/:id/edit" => "user_management#update"
  
  get "user_management/new" => "user_management#new"
  post "user_management/new" => "user_management#create"
  
  devise_for :users, :controllers => { registrations: 'registration' }
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  default_url_options :host => "example.com"

end

app/models/demande.rb
class Demande < ActiveRecord::Base
	enum service: {VS: "VS", EG: "EG", CTS: "CTS"}
	
	has_many :vs_demandes
	has_many :demande_egs
    has_many :demande_enfants
    belongs_to :famille, foreign_key: :famille_id, primary_key: :dossier_id
	belongs_to :motif
	belongs_to :user
	
	validates :service, :presence => {:message => "*Veuillez spécifier un service"}
	validates :famille_id, :presence => {:message => "*Veuillez spécifier une famille"}
	validates :frequence, :presence => {:message => "*Veuillez spécifier une fréquence"}
	validates :demandeur, :presence => {:message => "*Veuillez spécifier un demandeur"}
	validates :payee_par, :presence => {:message => "*Veuillez spécifier la personne qui paie"}
	validates :motif_id, :presence => {:message => "*Veuillez spécifier un motif"}
end

app/models/demande_eg.rb
class DemandeEg < ActiveRecord::Base
	belongs_to :demande
	validates :motif, :presence => {:message => "*Veuillez spécifier un motif"}
	validates :date_separation, :presence => {:message => "*Veuillez spécifier une date de séparation."}
	validates :description_enfant, :presence => {:message => "*Veuillez spécifier une description de l'enfant."}
	validates :attitude_parent, :presence => {:message => "*Veuillez spécifier l'attitude du parent."}
	validates :attitude_enfant, :presence => {:message => "*Veuillez spécifier l'attitude de l'enfant."}
end

app/models/enfant.rb
class Enfant < ActiveRecord::Base
	has_many :demandes

	validates :residence, :presence => {:message => "*Veuillez spécifier une résidence."}
	validates :nom, :presence => {:message => "*Veuillez spécifier le nom de l'enfant."}
	validates :date_naissance, :presence => {:message => "*Veuillez spécifier la date de naissance."}
end

app/models/famille.rb
class Famille < ActiveRecord::Base
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom de famille."}
	validates :dossier_id, :presence => {:message => "*Veuillez spécifier un numéro de dossier."}
	has_many :notes
	has_many :demandes, foreign_key: :famille_id, primary_key: :dossier_id
end

app/models/motif.rb
class Motif < ActiveRecord::Base
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom de motif."}
	has_many :demande
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :texte,      :presence => {:message => "*Veuillez spécifier du texte."}	
	validates :famille_id, :presence => {:message => "*Veuillez spécifier une famille."}
	validates :users_id,   :presence => {:message => "*Veuillez spécifier un utilisateur."}
	
	belongs_to :famille,  :foreign_key => "familles_id"
	belongs_to :createur, :class_name => "User", :foreign_key => "user_id"
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	enum statut: [:gardien, :tuteur, :visiteur, :acceuil]
	has_many :demandes

	has_many :parentinfos
    accepts_nested_attributes_for :parentinfos

	validates :statut, :presence => {:message => "*Veuillez spécifier un statut."}
	validates :date_naissance, :presence => {:message => "*Veuillez spécifier une date de naissance."}
	validates :nom, :presence => {:message => "*Veuillez spécifier un nom."}
	validates :demande_id, :presence => {:message => "*Veuillez spécifier un numéro de demande."}
end

app/models/parentinfo.rb
class Parentinfo < ActiveRecord::Base
	belongs_to :parent
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  belongs_to :role
  has_many :notes
  has_many :demandes
  validates :name, presence: true, length: { maximum: 50, minimum: 5, message: 'Le nom doit être entre 5 et 50 caractères' }
end

app/models/vs_demande.rb
class VsDemande < ActiveRecord::Base
	belongs_to :demande

	validates :motif_pv, :presence => {:message => "*Veuillez spécifier un motif"}
	validates :motivations_pv, :presence => {:message => "*Veuillez spécifier une motivation."}
	validates :attitude_parent_pv, :presence => {:message => "*Veuillez spécifier une attitude."}
	validates :motif_pg, :presence => {:message => "*Veuillez spécifier le motif."}
	validates :personnes_autorisees_pg, :presence => {:message => "*Veuillez spécifier les personnes autorisées"}
	validates :attitude_parent_pg, :presence => {:message => "*Veuillez spécifier une attitude"}
	validates :jeux_favoris_pg, :presence => {:message => "*Veuillez spécifier les jeux favoris."}
	validates :gout_alimentaire_pg, :presence => {:message => "*Veuillez spécifier les gouts alimentaires."}
	validates :reaction_visite_pg, :presence => {:message => "*Veuillez spécifier la réaction."}
	validates :attitude_enfant_pg, :presence => {:message => "*Veuillez spécifier l'attitude."}

end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  before_filter :authenticate_user!
  before_filter {:ensure_directeur! || :ensure_coordonnateur!}
  before_action :set_usager, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.all
  end
  
  def new
	set_role
  end
  
  def create
	set_role
	@user = User.new(new_usager_params)
	if @user.save
	  redirect_to action: "index"
	else
      render :"new"
	end
  end
  
  def edit
    @user = User.find(params[:id])
	set_role
  end
  
  def update
	@user = User.find(params[:id])
    if @user.update(usager_params)
		redirect_to action: "index"
	else
		render :"edit"
	end
  end
  
  def destroy
    if !(@user == current_user)
	  @user.destroy
	end
	redirect_to action: "index"
  end
  
  # Use callbacks to share common setup or constraints between actions.
  private
  def set_usager
	set_role
    @user = User.find(params[:id])
  end
  
  private
  def set_role
	if (current_user.role_id == 0)
		@roles = Role.all
	end
	if (current_user.role_id == 1)
		@roles = Role.where(['id=1 OR id=2'])
	end
  end

  private
  def usager_params
	params[:user][:role_id] = params[:user][:role_id].to_f
	if params[:user][:password].blank?
		params.require(:user).permit(:name, :role_id, :email)
	else
		params.require(:user).permit(:name, :role_id, :email, :password, :password_confirmation)
	end
  end
  
  private
  def new_usager_params
	params[:user][:role_id] = params[:user][:role_id].to_f
    params.require(:user).permit(:name, :role_id, :email, :password, :password_confirmation)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demande_egs_helper.rb
module DemandeEgsHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/helpers/motifs_helper.rb
module MotifsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/user_management/edit.html.erb
<h1 class="titleRQRSDA">Modification de compte</h1>
<div class="descriptionRQRSDA">
	<% @user.errors.each do |attr, msg| %>
		<% puts 'errors ared' + msg.to_s %>
		<li><%= msg %></li>
	<% end %><br />
	
    <%= form_for :user, html: { method: :put } do |f| %>
      <div class="field">
        <%= f.label :'Nom' %><br />
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :'Rôle' %><br />
		<%= f.select :role_id, options_from_collection_for_select(@roles, "id", "name") %>
      </div>

      <div class="field">
        <%= f.label :'Courriel' %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :'Nouveau mot de passe' %> <br />
        <%= f.password_field :password, autocomplete: "off" %>
          <em>Laissez vide pour ne pas le remplacer. (6 characters minimum)</em>
      </div>

      <div class="field">
        <%= f.label :'Confirmer nouveau mot de passe' %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Sauvegarder" %>
      </div>
    <% end %>
	<%= link_to 'Retour à la liste des comptes', user_management_index_path %>
</div>

app/views/user_management/index.html.erb
<h1 class="titleRQRSDA">Comptes</h1>
<div class="descriptionRQRSDA">
    <table>
      <thead>
        <tr>
          <th>Nom</th>
          <th>Courriel</th>
		  <th>Rôle</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
				<% if user.role_id == 0 %>
					<td>Directeur</td>
				<% end %>
				<% if user.role_id == 1 %>
					<td>Coordonnateur</td>
				<% end %>
				<% if user.role_id == 2 %>
					<td>Intervenant</td>
				<% end %>
				<% if ((current_user.role_id <= user.role_id) && (user != current_user)) %>
					<td><%= button_to 'Modifier', edit_user_management_path(user), method: :edit %></td>
					<td><%= button_to 'Supprimer', user_management_url(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
			</tr>
        <% end %>
      </tbody>
    </table>
	<%= link_to 'Créer', new_user_management_path %>
</div>

app/views/user_management/new.html.erb
<h1 class="titleRQRSDA">Création de compte</h1>

<div class="descriptionRQRSDA">
	<% if !@user.nil? %>
	<% @user.errors.each do |attr, msg| %>
		<% puts 'errors ared' + msg.to_s %>
		<li><%= msg %></li>
	<% end %><br />
	<% end %>

    <%= form_for :user, :url => {:controller => "user_management", :action => "new"} do |f| %>

      <div class="field">
        <%= f.label :'Nom' %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :'Rôle' %><br />
		<%= f.select :role_id, options_from_collection_for_select(@roles, "id", "name") %>
      </div>
      <div class="field">
        <%= f.label :'Courriel' %><br />
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :'Mot de passe' %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :'Confirmation du mot de passe' %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Sauvegarder" %>
      </div>
    <% end %>
	<%= link_to 'Retour à la liste des comptes', user_management_index_path %>
</div>